// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwDnPhE6cDqNs4sZJdcsoJ4JE6WeV_5BI',
    appId: '1:285342174001:web:446c2482f109b52d757e10',
    messagingSenderId: '285342174001',
    projectId: 'smallapps-da23c',
    authDomain: 'smallapps-da23c.firebaseapp.com',
    storageBucket: 'smallapps-da23c.appspot.com',
    measurementId: 'G-3V0P94WPLL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwTT2NK9G0JnuXjehf66caY0MC16gRxrs',
    appId: '1:285342174001:android:d5b0ee153437939f757e10',
    messagingSenderId: '285342174001',
    projectId: 'smallapps-da23c',
    storageBucket: 'smallapps-da23c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcwo_bt5Q4uo23QK4e6nlR7nCWDYiPD00',
    appId: '1:285342174001:ios:14a5deea0e43e994757e10',
    messagingSenderId: '285342174001',
    projectId: 'smallapps-da23c',
    storageBucket: 'smallapps-da23c.appspot.com',
    androidClientId: '285342174001-34rjcb0s8c25o82em6bhlha6m227rl7d.apps.googleusercontent.com',
    iosClientId: '285342174001-abpvifpa62g5ue06aojq0mo6ks2dbts1.apps.googleusercontent.com',
    iosBundleId: 'com.starland.cartomania',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcwo_bt5Q4uo23QK4e6nlR7nCWDYiPD00',
    appId: '1:285342174001:ios:14a5deea0e43e994757e10',
    messagingSenderId: '285342174001',
    projectId: 'smallapps-da23c',
    storageBucket: 'smallapps-da23c.appspot.com',
    androidClientId: '285342174001-34rjcb0s8c25o82em6bhlha6m227rl7d.apps.googleusercontent.com',
    iosClientId: '285342174001-abpvifpa62g5ue06aojq0mo6ks2dbts1.apps.googleusercontent.com',
    iosBundleId: 'com.starland.cartomania',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOfMQNljjn4hmBViCJCcIclQNDF7YcoYY',
    appId: '1:285342174001:web:6aeb3a331b29ab2c757e10',
    messagingSenderId: '285342174001',
    projectId: 'smallapps-da23c',
    authDomain: 'smallapps-da23c.firebaseapp.com',
    storageBucket: 'smallapps-da23c.appspot.com',
    measurementId: 'G-MLQW2EQXB5',
  );
}
